name: tii-octomap-server2-coverity

on:
  repository_dispatch:
  push:

jobs:
  coverity:
    runs-on: octomap-server2-self-hosted-coverity
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Coverity scan 👁️
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/tiiuae/fog-ros-baseimage-builder-coverity:main
          options: -e PROJECT_NAME=${{ github.event.repository.name }} -v ${{ github.workspace }}:/main_ws/src
          run: |
            /entrypoint-coverity.sh
